[env:esp32-s3-banana-leaf]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
    tttapa/Control Surface @ ^2.1.0
build_flags = 
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D USB_MANUFACTURER="\"Banana Leaf\""
    -D USB_PRODUCT="\"Banana-S3\""